### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by igas** [igas/faker#9]
- [ ] Add elixir first class docs
- [x] Remove json programming
- [ ] Remove application
- [ ] Add different modules to different langs
